#!/bin/bash

cd python-native

./configure #build a native version of Python to get pgen from
touch Include/Python-ast.h Python/Python-ast.c
make Parser/pgen #build a native version of Python to get pgen from

cd ..

if [[ "$*" =~ (^|[[:blank:]])(-h|--help)([[:blank:]]|$) ]]; then
    ./configure --help
    exit 1
fi

env FORCE_UNSAFE_CONFIGURE=1 ./configure --host=wasm32-unknown-wasi --target=wasm32-unknown-wasi CC="/home/clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04/bin/clang-16 -pthread --target=wasm32-unknown-wasi --sysroot /home/lind-wasm/glibc/sysroot -Wl,--import-memory,--export-memory,--max-memory=67108864,--export=__stack_pointer -D _FILE_OFFSET_BITS=64 -D __USE_LARGEFILE64 -g -O0" --without-termcap ac_cv_func_working_mktime=yes ac_cv_func_mmap_fixed_mapped=yes bash_cv_func_sigsetjmp=no ac_cv_func_localeconv=no ac_cv_func_uselocale=no ac_cv_func_setlocale=no ac_cv_func_newlocale=no ac_cv_have_chflags=no --verbose > configure.log

cp "./Modules/Setup.dist"  "./Modules/Setup"

touch Include/Python-ast.h Python/Python-ast.c

make AR="llvm-ar" ARFLAGS="crs" RANLIB="echo" CFLAGS="--debug" V=1 > check.log #will fail

cp python-native/Parser/pgen Parser/pgen && chmod +x Parser/pgen

make AR="llvm-ar" ARFLAGS="crs" RANLIB="echo" CFLAGS="--debug" V=1 >> check.log
